{
  "formatVersion": "1.1",
  "component": {
    "group": "org.psilynx",
    "module": "PsiKit",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "PsiKit-0.0.4.jar",
          "url": "PsiKit-0.0.4.jar",
          "size": 114463,
          "sha512": "191c0c9e06ed0e8da4d907dc93fd6fe44e1a77cb44d1d76088c30a589eb2c404be162973abc606f297ab2f08156c11f94c53027c5545333df943d51dcd35cbd5",
          "sha256": "eafe4bf2f672a034baf6eda7fcf7ca2ee13634059680d1218e593a23a87950ab",
          "sha1": "37df9ab7bd588857d19df054a5ab315ee27a8d0a",
          "md5": "39ba45fa2092534d83fe38fc042bbf91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        },
        {
          "group": "io.kaitai",
          "module": "kaitai-struct-runtime",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "PsiKit-0.0.4.jar",
          "url": "PsiKit-0.0.4.jar",
          "size": 114463,
          "sha512": "191c0c9e06ed0e8da4d907dc93fd6fe44e1a77cb44d1d76088c30a589eb2c404be162973abc606f297ab2f08156c11f94c53027c5545333df943d51dcd35cbd5",
          "sha256": "eafe4bf2f672a034baf6eda7fcf7ca2ee13634059680d1218e593a23a87950ab",
          "sha1": "37df9ab7bd588857d19df054a5ab315ee27a8d0a",
          "md5": "39ba45fa2092534d83fe38fc042bbf91"
        }
      ]
    }
  ]
}
