/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_psilynx_psikit_wpi_WPIUtilJNI */

#ifndef _Included_org_psilynx_psikit_wpi_WPIUtilJNI
#define _Included_org_psilynx_psikit_wpi_WPIUtilJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    checkMsvcRuntime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_checkMsvcRuntime
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    writeStderr
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_writeStderr
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    enableMockTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_enableMockTime
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    disableMockTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_disableMockTime
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    setMockTime
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_setMockTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    now
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_now
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    getSystemTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_getSystemTime
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    createEvent
 * Signature: (ZZ)I
 */
JNIEXPORT jint JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_createEvent
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    destroyEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_destroyEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    setEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_setEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    resetEvent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_resetEvent
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    createSemaphore
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_createSemaphore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    destroySemaphore
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_destroySemaphore
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    releaseSemaphore
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_releaseSemaphore
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    allocateRawFrame
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_allocateRawFrame
  (JNIEnv *, jclass);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    freeRawFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_freeRawFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    getRawFrameDataPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_getRawFrameDataPtr
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    setRawFrameData
 * Signature: (JLjava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_setRawFrameData
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    setRawFrameInfo
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_setRawFrameInfo
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    setRawFrameTime
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_setRawFrameTime
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    waitForObject
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_waitForObject
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    waitForObjectTimeout
 * Signature: (ID)Z
 */
JNIEXPORT jboolean JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_waitForObjectTimeout
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    waitForObjects
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_waitForObjects
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    waitForObjectsTimeout
 * Signature: ([ID)[I
 */
JNIEXPORT jintArray JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_waitForObjectsTimeout
  (JNIEnv *, jclass, jintArray, jdouble);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    createFileLogger
 * Signature: (Ljava/lang/String;JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_createFileLogger
  (JNIEnv *, jclass, jstring, jlong, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_WPIUtilJNI
 * Method:    freeFileLogger
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_WPIUtilJNI_freeFileLogger
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
