/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_psilynx_psikit_wpi_DataLogJNI */

#ifndef _Included_org_psilynx_psikit_wpi_DataLogJNI
#define _Included_org_psilynx_psikit_wpi_DataLogJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    bgCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;DLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_bgCreate
  (JNIEnv *, jclass, jstring, jstring, jdouble, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    bgSetFilename
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_bgSetFilename
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    fgCreate
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_fgCreate
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    fgCreateMemory
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_fgCreateMemory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    copyWriteBuffer
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_copyWriteBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    pause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_pause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    resume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_resume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    addSchema
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_addSchema
  (JNIEnv *, jclass, jlong, jstring, jstring, jbyteArray, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    addSchemaString
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_addSchemaString
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    start
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_start
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    finish
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_finish
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    setMetadata
 * Signature: (JILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_setMetadata
  (JNIEnv *, jclass, jlong, jint, jstring, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendRaw
 * Signature: (JI[BIIJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendRaw
  (JNIEnv *, jclass, jlong, jint, jbyteArray, jint, jint, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendRawBuffer
 * Signature: (JILjava/nio/ByteBuffer;IIJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendRawBuffer
  (JNIEnv *, jclass, jlong, jint, jobject, jint, jint, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendBoolean
 * Signature: (JIZJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendBoolean
  (JNIEnv *, jclass, jlong, jint, jboolean, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendInteger
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendInteger
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendFloat
 * Signature: (JIFJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendFloat
  (JNIEnv *, jclass, jlong, jint, jfloat, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendDouble
 * Signature: (JIDJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendDouble
  (JNIEnv *, jclass, jlong, jint, jdouble, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendString
 * Signature: (JILjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendString
  (JNIEnv *, jclass, jlong, jint, jstring, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendBooleanArray
 * Signature: (JI[ZJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendBooleanArray
  (JNIEnv *, jclass, jlong, jint, jbooleanArray, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendIntegerArray
 * Signature: (JI[JJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendIntegerArray
  (JNIEnv *, jclass, jlong, jint, jlongArray, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendFloatArray
 * Signature: (JI[FJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendFloatArray
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendDoubleArray
 * Signature: (JI[DJ)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendDoubleArray
  (JNIEnv *, jclass, jlong, jint, jdoubleArray, jlong);

/*
 * Class:     org_psilynx_psikit_wpi_DataLogJNI
 * Method:    appendStringArray
 * Signature: (JI[Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_psilynx_psikit_wpi_DataLogJNI_appendStringArray
  (JNIEnv *, jclass, jlong, jint, jobjectArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
