{
  "formatVersion": "1.1",
  "component": {
    "group": "org.psilynx",
    "module": "psikit",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "psikit-0.0.2.jar",
          "url": "psikit-0.0.2.jar",
          "size": 100772,
          "sha512": "8e9319b416fc46186b6bdd8b86c8e7597c91563529b7f53186645b3807f24d1149b37e72190b276c912180193a4f99ff3b93d2217abc6cf20a0e18e9f03c8540",
          "sha256": "301d0ebd261f10987e925ac1ea9a9712408606020436794bab32eb852d728438",
          "sha1": "062fd36ec70f16b63a648aa7bb10aef9e255e843",
          "md5": "b72083c461d46a163f3972a5446f8ebe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.7"
          }
        }
      ],
      "files": [
        {
          "name": "psikit-0.0.2.jar",
          "url": "psikit-0.0.2.jar",
          "size": 100772,
          "sha512": "8e9319b416fc46186b6bdd8b86c8e7597c91563529b7f53186645b3807f24d1149b37e72190b276c912180193a4f99ff3b93d2217abc6cf20a0e18e9f03c8540",
          "sha256": "301d0ebd261f10987e925ac1ea9a9712408606020436794bab32eb852d728438",
          "sha1": "062fd36ec70f16b63a648aa7bb10aef9e255e843",
          "md5": "b72083c461d46a163f3972a5446f8ebe"
        }
      ]
    }
  ]
}
